// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: testEnum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MySutyProto {

  /// <summary>Holder for reflection information generated from testEnum.proto</summary>
  public static partial class TestEnumReflection {

    #region Descriptor
    /// <summary>File descriptor for testEnum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestEnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg50ZXN0RW51bS5wcm90bxILbXlTdXR5UHJvdG8iigEKBFRlc3QSCgoCYWEY",
            "ASABKAUSCgoCdHQYAiABKAISCgoCZ2cYAyABKAESCgoCbW0YBCABKAkSCgoC",
            "YmIYBSABKAgSCwoDYXJyGAYgASgMEioKCHR5cGVUZXN0GAcgASgOMhgubXlT",
            "dXR5UHJvdG8uRW51VGVzdFR5cGUSDQoFYXJyVFQYCCADKAIqKgoLRW51VGVz",
            "dFR5cGUSBwoDT25lEAASBwoDVHdvEAESCQoFVGhyZWUQAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MySutyProto.EnuTestType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MySutyProto.Test), global::MySutyProto.Test.Parser, new[]{ "Aa", "Tt", "Gg", "Mm", "Bb", "Arr", "TypeTest", "ArrTT" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum EnuTestType {
    [pbr::OriginalName("One")] One = 0,
    [pbr::OriginalName("Two")] Two = 1,
    [pbr::OriginalName("Three")] Three = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Test : pb::IMessage<Test>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Test> _parser = new pb::MessageParser<Test>(() => new Test());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Test> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MySutyProto.TestEnumReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test(Test other) : this() {
      aa_ = other.aa_;
      tt_ = other.tt_;
      gg_ = other.gg_;
      mm_ = other.mm_;
      bb_ = other.bb_;
      arr_ = other.arr_;
      typeTest_ = other.typeTest_;
      arrTT_ = other.arrTT_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test Clone() {
      return new Test(this);
    }

    /// <summary>Field number for the "aa" field.</summary>
    public const int AaFieldNumber = 1;
    private int aa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Aa {
      get { return aa_; }
      set {
        aa_ = value;
      }
    }

    /// <summary>Field number for the "tt" field.</summary>
    public const int TtFieldNumber = 2;
    private float tt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Tt {
      get { return tt_; }
      set {
        tt_ = value;
      }
    }

    /// <summary>Field number for the "gg" field.</summary>
    public const int GgFieldNumber = 3;
    private double gg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Gg {
      get { return gg_; }
      set {
        gg_ = value;
      }
    }

    /// <summary>Field number for the "mm" field.</summary>
    public const int MmFieldNumber = 4;
    private string mm_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mm {
      get { return mm_; }
      set {
        mm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bb" field.</summary>
    public const int BbFieldNumber = 5;
    private bool bb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Bb {
      get { return bb_; }
      set {
        bb_ = value;
      }
    }

    /// <summary>Field number for the "arr" field.</summary>
    public const int ArrFieldNumber = 6;
    private pb::ByteString arr_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Arr {
      get { return arr_; }
      set {
        arr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "typeTest" field.</summary>
    public const int TypeTestFieldNumber = 7;
    private global::MySutyProto.EnuTestType typeTest_ = global::MySutyProto.EnuTestType.One;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MySutyProto.EnuTestType TypeTest {
      get { return typeTest_; }
      set {
        typeTest_ = value;
      }
    }

    /// <summary>Field number for the "arrTT" field.</summary>
    public const int ArrTTFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_arrTT_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> arrTT_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> ArrTT {
      get { return arrTT_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Test);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Test other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Aa != other.Aa) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Tt, other.Tt)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Gg, other.Gg)) return false;
      if (Mm != other.Mm) return false;
      if (Bb != other.Bb) return false;
      if (Arr != other.Arr) return false;
      if (TypeTest != other.TypeTest) return false;
      if(!arrTT_.Equals(other.arrTT_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Aa != 0) hash ^= Aa.GetHashCode();
      if (Tt != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Tt);
      if (Gg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Gg);
      if (Mm.Length != 0) hash ^= Mm.GetHashCode();
      if (Bb != false) hash ^= Bb.GetHashCode();
      if (Arr.Length != 0) hash ^= Arr.GetHashCode();
      if (TypeTest != global::MySutyProto.EnuTestType.One) hash ^= TypeTest.GetHashCode();
      hash ^= arrTT_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Aa != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Aa);
      }
      if (Tt != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Tt);
      }
      if (Gg != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Gg);
      }
      if (Mm.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mm);
      }
      if (Bb != false) {
        output.WriteRawTag(40);
        output.WriteBool(Bb);
      }
      if (Arr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Arr);
      }
      if (TypeTest != global::MySutyProto.EnuTestType.One) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TypeTest);
      }
      arrTT_.WriteTo(output, _repeated_arrTT_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Aa != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Aa);
      }
      if (Tt != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Tt);
      }
      if (Gg != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Gg);
      }
      if (Mm.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mm);
      }
      if (Bb != false) {
        output.WriteRawTag(40);
        output.WriteBool(Bb);
      }
      if (Arr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Arr);
      }
      if (TypeTest != global::MySutyProto.EnuTestType.One) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TypeTest);
      }
      arrTT_.WriteTo(ref output, _repeated_arrTT_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Aa != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Aa);
      }
      if (Tt != 0F) {
        size += 1 + 4;
      }
      if (Gg != 0D) {
        size += 1 + 8;
      }
      if (Mm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mm);
      }
      if (Bb != false) {
        size += 1 + 1;
      }
      if (Arr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Arr);
      }
      if (TypeTest != global::MySutyProto.EnuTestType.One) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TypeTest);
      }
      size += arrTT_.CalculateSize(_repeated_arrTT_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Test other) {
      if (other == null) {
        return;
      }
      if (other.Aa != 0) {
        Aa = other.Aa;
      }
      if (other.Tt != 0F) {
        Tt = other.Tt;
      }
      if (other.Gg != 0D) {
        Gg = other.Gg;
      }
      if (other.Mm.Length != 0) {
        Mm = other.Mm;
      }
      if (other.Bb != false) {
        Bb = other.Bb;
      }
      if (other.Arr.Length != 0) {
        Arr = other.Arr;
      }
      if (other.TypeTest != global::MySutyProto.EnuTestType.One) {
        TypeTest = other.TypeTest;
      }
      arrTT_.Add(other.arrTT_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Aa = input.ReadInt32();
            break;
          }
          case 21: {
            Tt = input.ReadFloat();
            break;
          }
          case 25: {
            Gg = input.ReadDouble();
            break;
          }
          case 34: {
            Mm = input.ReadString();
            break;
          }
          case 40: {
            Bb = input.ReadBool();
            break;
          }
          case 50: {
            Arr = input.ReadBytes();
            break;
          }
          case 56: {
            TypeTest = (global::MySutyProto.EnuTestType) input.ReadEnum();
            break;
          }
          case 66:
          case 69: {
            arrTT_.AddEntriesFrom(input, _repeated_arrTT_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Aa = input.ReadInt32();
            break;
          }
          case 21: {
            Tt = input.ReadFloat();
            break;
          }
          case 25: {
            Gg = input.ReadDouble();
            break;
          }
          case 34: {
            Mm = input.ReadString();
            break;
          }
          case 40: {
            Bb = input.ReadBool();
            break;
          }
          case 50: {
            Arr = input.ReadBytes();
            break;
          }
          case 56: {
            TypeTest = (global::MySutyProto.EnuTestType) input.ReadEnum();
            break;
          }
          case 66:
          case 69: {
            arrTT_.AddEntriesFrom(ref input, _repeated_arrTT_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
