// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: testProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MySutyProto {

  /// <summary>Holder for reflection information generated from testProto.proto</summary>
  public static partial class TestProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for testProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TestProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg90ZXN0UHJvdG8ucHJvdG8SC215U3V0eVByb3RvGhN0ZXN0RW51bVByb3Rv",
            "LnByb3RvIp8CCghUZXN0Mk1zZxIKCgJhYRgBIAEoBRIKCgJ0dBgCIAEoAhIK",
            "CgJnZxgDIAEoARIKCgJtbRgEIAEoCRIKCgJiYhgFIAEoCBILCgNhcnIYBiAB",
            "KAwSKwoIdHlwZVRlc3QYByABKA4yGS5teVN1dHlQcm90bzIuRW51VGVzdFR5",
            "cGUSDQoFYXJyVFQYCCADKAISCgoCYXQYCSABKBESLwoFdHRNYXAYCiADKAsy",
            "IC5teVN1dHlQcm90by5UZXN0Mk1zZy5UdE1hcEVudHJ5EiMKBG1zZzEYCyAB",
            "KAsyFS5teVN1dHlQcm90bzIuVGVzdE1zZxosCgpUdE1hcEVudHJ5EgsKA2tl",
            "eRgBIAEoBRINCgV2YWx1ZRgCIAEoAjoCOAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::MySutyProto2.TestEnumProtoReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MySutyProto.Test2Msg), global::MySutyProto.Test2Msg.Parser, new[]{ "Aa", "Tt", "Gg", "Mm", "Bb", "Arr", "TypeTest", "ArrTT", "At", "TtMap", "Msg1" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Test2Msg : pb::IMessage<Test2Msg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Test2Msg> _parser = new pb::MessageParser<Test2Msg>(() => new Test2Msg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Test2Msg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MySutyProto.TestProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test2Msg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test2Msg(Test2Msg other) : this() {
      aa_ = other.aa_;
      tt_ = other.tt_;
      gg_ = other.gg_;
      mm_ = other.mm_;
      bb_ = other.bb_;
      arr_ = other.arr_;
      typeTest_ = other.typeTest_;
      arrTT_ = other.arrTT_.Clone();
      at_ = other.at_;
      ttMap_ = other.ttMap_.Clone();
      msg1_ = other.msg1_ != null ? other.msg1_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Test2Msg Clone() {
      return new Test2Msg(this);
    }

    /// <summary>Field number for the "aa" field.</summary>
    public const int AaFieldNumber = 1;
    private int aa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Aa {
      get { return aa_; }
      set {
        aa_ = value;
      }
    }

    /// <summary>Field number for the "tt" field.</summary>
    public const int TtFieldNumber = 2;
    private float tt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Tt {
      get { return tt_; }
      set {
        tt_ = value;
      }
    }

    /// <summary>Field number for the "gg" field.</summary>
    public const int GgFieldNumber = 3;
    private double gg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Gg {
      get { return gg_; }
      set {
        gg_ = value;
      }
    }

    /// <summary>Field number for the "mm" field.</summary>
    public const int MmFieldNumber = 4;
    private string mm_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Mm {
      get { return mm_; }
      set {
        mm_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bb" field.</summary>
    public const int BbFieldNumber = 5;
    private bool bb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Bb {
      get { return bb_; }
      set {
        bb_ = value;
      }
    }

    /// <summary>Field number for the "arr" field.</summary>
    public const int ArrFieldNumber = 6;
    private pb::ByteString arr_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Arr {
      get { return arr_; }
      set {
        arr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "typeTest" field.</summary>
    public const int TypeTestFieldNumber = 7;
    private global::MySutyProto2.EnuTestType typeTest_ = global::MySutyProto2.EnuTestType.One;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MySutyProto2.EnuTestType TypeTest {
      get { return typeTest_; }
      set {
        typeTest_ = value;
      }
    }

    /// <summary>Field number for the "arrTT" field.</summary>
    public const int ArrTTFieldNumber = 8;
    private static readonly pb::FieldCodec<float> _repeated_arrTT_codec
        = pb::FieldCodec.ForFloat(66);
    private readonly pbc::RepeatedField<float> arrTT_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> ArrTT {
      get { return arrTT_; }
    }

    /// <summary>Field number for the "at" field.</summary>
    public const int AtFieldNumber = 9;
    private int at_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int At {
      get { return at_; }
      set {
        at_ = value;
      }
    }

    /// <summary>Field number for the "ttMap" field.</summary>
    public const int TtMapFieldNumber = 10;
    private static readonly pbc::MapField<int, float>.Codec _map_ttMap_codec
        = new pbc::MapField<int, float>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForFloat(21, 0F), 82);
    private readonly pbc::MapField<int, float> ttMap_ = new pbc::MapField<int, float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, float> TtMap {
      get { return ttMap_; }
    }

    /// <summary>Field number for the "msg1" field.</summary>
    public const int Msg1FieldNumber = 11;
    private global::MySutyProto2.TestMsg msg1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::MySutyProto2.TestMsg Msg1 {
      get { return msg1_; }
      set {
        msg1_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Test2Msg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Test2Msg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Aa != other.Aa) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Tt, other.Tt)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Gg, other.Gg)) return false;
      if (Mm != other.Mm) return false;
      if (Bb != other.Bb) return false;
      if (Arr != other.Arr) return false;
      if (TypeTest != other.TypeTest) return false;
      if(!arrTT_.Equals(other.arrTT_)) return false;
      if (At != other.At) return false;
      if (!TtMap.Equals(other.TtMap)) return false;
      if (!object.Equals(Msg1, other.Msg1)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Aa != 0) hash ^= Aa.GetHashCode();
      if (Tt != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Tt);
      if (Gg != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Gg);
      if (Mm.Length != 0) hash ^= Mm.GetHashCode();
      if (Bb != false) hash ^= Bb.GetHashCode();
      if (Arr.Length != 0) hash ^= Arr.GetHashCode();
      if (TypeTest != global::MySutyProto2.EnuTestType.One) hash ^= TypeTest.GetHashCode();
      hash ^= arrTT_.GetHashCode();
      if (At != 0) hash ^= At.GetHashCode();
      hash ^= TtMap.GetHashCode();
      if (msg1_ != null) hash ^= Msg1.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Aa != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Aa);
      }
      if (Tt != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Tt);
      }
      if (Gg != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Gg);
      }
      if (Mm.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mm);
      }
      if (Bb != false) {
        output.WriteRawTag(40);
        output.WriteBool(Bb);
      }
      if (Arr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Arr);
      }
      if (TypeTest != global::MySutyProto2.EnuTestType.One) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TypeTest);
      }
      arrTT_.WriteTo(output, _repeated_arrTT_codec);
      if (At != 0) {
        output.WriteRawTag(72);
        output.WriteSInt32(At);
      }
      ttMap_.WriteTo(output, _map_ttMap_codec);
      if (msg1_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Msg1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Aa != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Aa);
      }
      if (Tt != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Tt);
      }
      if (Gg != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Gg);
      }
      if (Mm.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mm);
      }
      if (Bb != false) {
        output.WriteRawTag(40);
        output.WriteBool(Bb);
      }
      if (Arr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Arr);
      }
      if (TypeTest != global::MySutyProto2.EnuTestType.One) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TypeTest);
      }
      arrTT_.WriteTo(ref output, _repeated_arrTT_codec);
      if (At != 0) {
        output.WriteRawTag(72);
        output.WriteSInt32(At);
      }
      ttMap_.WriteTo(ref output, _map_ttMap_codec);
      if (msg1_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(Msg1);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Aa != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Aa);
      }
      if (Tt != 0F) {
        size += 1 + 4;
      }
      if (Gg != 0D) {
        size += 1 + 8;
      }
      if (Mm.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mm);
      }
      if (Bb != false) {
        size += 1 + 1;
      }
      if (Arr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Arr);
      }
      if (TypeTest != global::MySutyProto2.EnuTestType.One) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TypeTest);
      }
      size += arrTT_.CalculateSize(_repeated_arrTT_codec);
      if (At != 0) {
        size += 1 + pb::CodedOutputStream.ComputeSInt32Size(At);
      }
      size += ttMap_.CalculateSize(_map_ttMap_codec);
      if (msg1_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Msg1);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Test2Msg other) {
      if (other == null) {
        return;
      }
      if (other.Aa != 0) {
        Aa = other.Aa;
      }
      if (other.Tt != 0F) {
        Tt = other.Tt;
      }
      if (other.Gg != 0D) {
        Gg = other.Gg;
      }
      if (other.Mm.Length != 0) {
        Mm = other.Mm;
      }
      if (other.Bb != false) {
        Bb = other.Bb;
      }
      if (other.Arr.Length != 0) {
        Arr = other.Arr;
      }
      if (other.TypeTest != global::MySutyProto2.EnuTestType.One) {
        TypeTest = other.TypeTest;
      }
      arrTT_.Add(other.arrTT_);
      if (other.At != 0) {
        At = other.At;
      }
      ttMap_.MergeFrom(other.ttMap_);
      if (other.msg1_ != null) {
        if (msg1_ == null) {
          Msg1 = new global::MySutyProto2.TestMsg();
        }
        Msg1.MergeFrom(other.Msg1);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Aa = input.ReadInt32();
            break;
          }
          case 21: {
            Tt = input.ReadFloat();
            break;
          }
          case 25: {
            Gg = input.ReadDouble();
            break;
          }
          case 34: {
            Mm = input.ReadString();
            break;
          }
          case 40: {
            Bb = input.ReadBool();
            break;
          }
          case 50: {
            Arr = input.ReadBytes();
            break;
          }
          case 56: {
            TypeTest = (global::MySutyProto2.EnuTestType) input.ReadEnum();
            break;
          }
          case 66:
          case 69: {
            arrTT_.AddEntriesFrom(input, _repeated_arrTT_codec);
            break;
          }
          case 72: {
            At = input.ReadSInt32();
            break;
          }
          case 82: {
            ttMap_.AddEntriesFrom(input, _map_ttMap_codec);
            break;
          }
          case 90: {
            if (msg1_ == null) {
              Msg1 = new global::MySutyProto2.TestMsg();
            }
            input.ReadMessage(Msg1);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Aa = input.ReadInt32();
            break;
          }
          case 21: {
            Tt = input.ReadFloat();
            break;
          }
          case 25: {
            Gg = input.ReadDouble();
            break;
          }
          case 34: {
            Mm = input.ReadString();
            break;
          }
          case 40: {
            Bb = input.ReadBool();
            break;
          }
          case 50: {
            Arr = input.ReadBytes();
            break;
          }
          case 56: {
            TypeTest = (global::MySutyProto2.EnuTestType) input.ReadEnum();
            break;
          }
          case 66:
          case 69: {
            arrTT_.AddEntriesFrom(ref input, _repeated_arrTT_codec);
            break;
          }
          case 72: {
            At = input.ReadSInt32();
            break;
          }
          case 82: {
            ttMap_.AddEntriesFrom(ref input, _map_ttMap_codec);
            break;
          }
          case 90: {
            if (msg1_ == null) {
              Msg1 = new global::MySutyProto2.TestMsg();
            }
            input.ReadMessage(Msg1);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
